// <auto-generated />
namespace _24Hr.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class addingModifiedUtc : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addingModifiedUtc));
        
        string IMigrationMetadata.Id
        {
            get { return "202102051559532_addingModifiedUtc"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
